#!/bin/bash
#PBS -l nodes=1:ppn=36
#PBS -l walltime=12:00:00
#PBS -o stdout.$PBS_JOBID
#PBS -e stderr.$PBS_JOBID

#while read line; do
#qsub viper.pbs -v line="$line"
#done < names.txt

#Move to wherever your files are
cd $VSC_SCRATCH

#Activate conda environment
source activate viper

#Make sure programs in conda viper environment are found first in PATH
export PATH="$CONDA_PREFIX/bin:$PATH"

#Run viper.sh script with desired options
viper.sh -1 $line.R1.fastq.gz -2 $line.R2.fastq.gz -x 130 -p /path/to/primer/file -g /path/to/host/genome \
	--triple-assembly -d /path/to/diamond/database -o $line -t 36